//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VestnikVZClient.zakazky {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdRequest", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VestnikVZClient.zakazky.ListFormsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VestnikVZClient.zakazky.GetFormDocumentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VestnikVZClient.zakazky.GetVersionRequest))]
    public partial class UserIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListFormsRequest", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class ListFormsRequest : VestnikVZClient.zakazky.UserIdRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VestnikVZClient.zakazky.QueryParameter[] QueryParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryName {
            get {
                return this.QueryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryNameField, value) != true)) {
                    this.QueryNameField = value;
                    this.RaisePropertyChanged("QueryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VestnikVZClient.zakazky.QueryParameter[] QueryParameters {
            get {
                return this.QueryParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryParametersField, value) != true)) {
                    this.QueryParametersField = value;
                    this.RaisePropertyChanged("QueryParameters");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFormDocumentRequest", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class GetFormDocumentRequest : VestnikVZClient.zakazky.UserIdRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormId {
            get {
                return this.FormIdField;
            }
            set {
                if ((this.FormIdField.Equals(value) != true)) {
                    this.FormIdField = value;
                    this.RaisePropertyChanged("FormId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormatVersion {
            get {
                return this.FormatVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatVersionField, value) != true)) {
                    this.FormatVersionField = value;
                    this.RaisePropertyChanged("FormatVersion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVersionRequest", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class GetVersionRequest : VestnikVZClient.zakazky.UserIdRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParameter", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class QueryParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VestnikVZClient.zakazky.ListFormsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VestnikVZClient.zakazky.GetFormDocumentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VestnikVZClient.zakazky.GetVersionResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListFormsResponse", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class ListFormsResponse : VestnikVZClient.zakazky.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VestnikVZClient.zakazky.FormInfo[] FormsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VestnikVZClient.zakazky.FormInfo[] Forms {
            get {
                return this.FormsField;
            }
            set {
                if ((object.ReferenceEquals(this.FormsField, value) != true)) {
                    this.FormsField = value;
                    this.RaisePropertyChanged("Forms");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFormDocumentResponse", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class GetFormDocumentResponse : VestnikVZClient.zakazky.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FormDocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FormDocument {
            get {
                return this.FormDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.FormDocumentField, value) != true)) {
                    this.FormDocumentField = value;
                    this.RaisePropertyChanged("FormDocument");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVersionResponse", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class GetVersionResponse : VestnikVZClient.zakazky.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VestnikVZClient.zakazky.AppVersion VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VestnikVZClient.zakazky.AppVersion Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppVersion", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class AppVersion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VestnikVZClient.zakazky.DocFormat[] SupportedDocumentFormatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VestnikVZClient.zakazky.DocFormat[] SupportedDocumentFormats {
            get {
                return this.SupportedDocumentFormatsField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportedDocumentFormatsField, value) != true)) {
                    this.SupportedDocumentFormatsField = value;
                    this.RaisePropertyChanged("SupportedDocumentFormats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormInfo", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class FormInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocFormat", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class DocFormat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamespaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VestnikVZClient.zakazky.Form[] SupportedFormsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XsdPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namespace {
            get {
                return this.NamespaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NamespaceField, value) != true)) {
                    this.NamespaceField = value;
                    this.RaisePropertyChanged("Namespace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VestnikVZClient.zakazky.Form[] SupportedForms {
            get {
                return this.SupportedFormsField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportedFormsField, value) != true)) {
                    this.SupportedFormsField = value;
                    this.RaisePropertyChanged("SupportedForms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XsdPath {
            get {
                return this.XsdPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XsdPathField, value) != true)) {
                    this.XsdPathField = value;
                    this.RaisePropertyChanged("XsdPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Form", Namespace="http://www.ness.cz/schemas/isvzus")]
    [System.SerializableAttribute()]
    public partial class Form : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XsdNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XsdName {
            get {
                return this.XsdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.XsdNameField, value) != true)) {
                    this.XsdNameField = value;
                    this.RaisePropertyChanged("XsdName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ness.cz/schemas/isvzus/ExportForms", ConfigurationName="zakazky.IExportForms")]
    public interface IExportForms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ness.cz/schemas/isvzus/ExportForms/IExportForms/GetVersion", ReplyAction="http://www.ness.cz/schemas/isvzus/ExportForms/IExportForms/GetVersionResponse")]
        VestnikVZClient.zakazky.GetVersionResponse GetVersion(VestnikVZClient.zakazky.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ness.cz/schemas/isvzus/ExportForms/IExportForms/ListForms", ReplyAction="http://www.ness.cz/schemas/isvzus/ExportForms/IExportForms/ListFormsResponse")]
        VestnikVZClient.zakazky.ListFormsResponse ListForms(VestnikVZClient.zakazky.ListFormsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ness.cz/schemas/isvzus/ExportForms/IExportForms/GetFormDocument", ReplyAction="http://www.ness.cz/schemas/isvzus/ExportForms/IExportForms/GetFormDocumentRespons" +
            "e")]
        VestnikVZClient.zakazky.GetFormDocumentResponse GetFormDocument(VestnikVZClient.zakazky.GetFormDocumentRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExportFormsChannel : VestnikVZClient.zakazky.IExportForms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportFormsClient : System.ServiceModel.ClientBase<VestnikVZClient.zakazky.IExportForms>, VestnikVZClient.zakazky.IExportForms {
        
        public ExportFormsClient() {
        }
        
        public ExportFormsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportFormsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportFormsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportFormsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VestnikVZClient.zakazky.GetVersionResponse GetVersion(VestnikVZClient.zakazky.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public VestnikVZClient.zakazky.ListFormsResponse ListForms(VestnikVZClient.zakazky.ListFormsRequest request) {
            return base.Channel.ListForms(request);
        }
        
        public VestnikVZClient.zakazky.GetFormDocumentResponse GetFormDocument(VestnikVZClient.zakazky.GetFormDocumentRequest request) {
            return base.Channel.GetFormDocument(request);
        }
    }
}
